---
ai_context_version: 1.1

# Repo-specific AI context.
# Do NOT copy this file unchanged into other repos; adjust project.name/role/paths first.

project:
  name: metarepo
  summary: Architecture source + internal contract constitution + templates/policies.
  role: control_plane
  primary_language: mixed
  visibility: internal

heimgewebe:
  axis: [Contracts, Motorik, Decisions]
  fleet:
    enabled: true
  wgx:
    profile_expected: true
    guard_smoke_expected: true

interfaces:
  consumes:
    - "fleet state (reports/findings)"
  produces:
    - "internal contracts (contracts/*.schema.json)"
    - "CI templates (wgx-guard.yml, wgx-smoke.yml)"
    - "architecture docs / ADRs"

contracts:
  schemas:
    - path: "contracts/*.schema.json"
      note: "Internal canonical contracts live here."

dependencies:
  internal:
    - name: wgx
      relationship: uses
      interface: [reusable_workflows]
  external:
    - name: markdown

boundaries:
  not_responsible_for:
    - "External protobuf APIs (contracts-mirror)."
  dangerous_assumptions:
    - "Assume docs reflect reality; verify via fleet scans."

conventions:
  branching: "main, feature/*"
  commit_prefix: "metarepo"
  ci_platform: github_actions

documentation:
  adr: docs/adr/
  runbook: docs/runbook.md

ai_guidance:
  do:
    - prefer workflow_call for reuse and pin external actions
  dont:
    - duplicate shared logic across repos
