---
name: Notify Plexer

"on":
  workflow_call:
    inputs:
      event_type:
        description: "Logical event type, e.g. ci.result"
        required: true
        type: string
      status:
        description: "Optional status field for payload"
        required: false
        type: string
      payload_json:
        description: "Additional JSON string to merge into payload (overrides defaults on key collision)"
        required: false
        type: string
      plexer_url:
        description: "Base URL of Plexer (e.g. https://plexer.local)"
        required: true
        type: string
    secrets:
      PLEXER_TOKEN:
        required: false

jobs:
  notify-plexer:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build event payload
        id: build
        env:
          INPUT_EVENT_TYPE: ${{ inputs.event_type }}
          INPUT_STATUS: ${{ inputs.status || '' }}
          INPUT_PAYLOAD_JSON: ${{ inputs.payload_json || '' }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          python3 -c '
          import json, os, datetime

          def get_env(key, default=""):
              return os.environ.get(key, default)

          ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

          payload = {
              "ts": ts,
              "status": get_env("INPUT_STATUS"),
              "workflow": get_env("GITHUB_WORKFLOW"),
              "run_id": get_env("GITHUB_RUN_ID"),
              "run_attempt": get_env("GITHUB_RUN_ATTEMPT"),
              "ref": get_env("GITHUB_REF"),
              "sha": get_env("GITHUB_SHA")
          }

          payload_json_str = get_env("INPUT_PAYLOAD_JSON")
          if payload_json_str:
              try:
                  extra = json.loads(payload_json_str)
                  if isinstance(extra, dict):
                      payload.update(extra)
                  else:
                      print("::warning::payload_json input is not a dictionary. Ignoring.")
              except json.JSONDecodeError:
                  print("::warning::payload_json input is invalid JSON. Ignoring.")

          event = {
              "type": get_env("INPUT_EVENT_TYPE"),
              "source": get_env("GITHUB_REPOSITORY"),
              "timestamp": ts,
              "payload": payload
          }

          with open("event.json", "w") as f:
              json.dump(event, f)
          '
          echo "payload<<EOF" >> "$GITHUB_OUTPUT"
          cat event.json >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: POST to Plexer
        env:
          PLEXER_URL: ${{ inputs.plexer_url }}
          PLEXER_TOKEN: ${{ secrets.PLEXER_TOKEN }}
        run: |
          set -euo pipefail
          if [ -z "${PLEXER_URL:-}" ]; then
            echo "PLEXER_URL is required"
            exit 1
          fi

          header_auth=""
          if [ -n "${PLEXER_TOKEN:-}" ]; then
            header_auth="-H \"Authorization: Bearer ${PLEXER_TOKEN}\""
          fi

          # shellcheck disable=SC2086
          curl -sS -X POST \
            -H "Content-Type: application/json" \
            ${header_auth} \
            "${PLEXER_URL%/}/events" \
            -d @"event.json"
