---
name: 'Setup yq'
description: 'Install yq using version from toolchain.versions.yml and verify checksum'
inputs:
  github-token:
    description: 'GitHub token for API authentication (to avoid rate limits)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Load yq version pin
      shell: bash
      run: |
        # Determine repo root - composite actions run in caller's workspace
        # GITHUB_WORKSPACE is set by GitHub Actions and points to the checked-out repo
        REPO_ROOT="${GITHUB_WORKSPACE:-.}"
        TOOLCHAIN_FILE="${REPO_ROOT}/toolchain.versions.yml"
        
        if [[ ! -f "${TOOLCHAIN_FILE}" ]]; then
          echo "toolchain.versions.yml not found at ${TOOLCHAIN_FILE}" >&2
          echo "Current directory: $(pwd)" >&2
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE:-<not set>}" >&2
          echo "Contents of repo root:" >&2
          ls -la "${REPO_ROOT}" | head -20 >&2
          exit 1
        fi

        # Extract yq version using robust grep/sed to avoid python dependency
        # Handles: yq: "v4.49.2" # comment
        # Logic mirrors scripts/tools/just-pin.sh:
        # 1. Strip key
        # 2. Strip comments
        # 3. Trim whitespace
        # 4. Strip quotes
        YQ_VER=$(grep -E '^\s*yq:' "${TOOLCHAIN_FILE}" | \
          sed -E 's/^\s*[^:]+:\s*//; s/#.*$//; s/^[[:space:]]*//; s/[[:space:]]*$//; s/^"//; s/"$//; s/^'\''//; s/'\''$//' | \
          tr -d '\n\r')

        if [[ -z "${YQ_VER}" ]]; then
           echo "Failed to extract yq version from toolchain.versions.yml" >&2
           exit 1
        fi

        echo "YQ_VERSION=${YQ_VER}" >> "$GITHUB_ENV"
        echo "Resolved yq version ${YQ_VER}"

    - name: Cache yq binary
      uses: actions/cache@v4
      with:
        path: ~/.local/bin/yq
        # Use GITHUB_WORKSPACE to ensure consistent path resolution across composite action calls
        key: ${{ runner.os }}-yq-${{ hashFiles(format('{0}/toolchain.versions.yml', github.workspace)) }}
        restore-keys: |
          ${{ runner.os }}-yq-
          yq-

    - name: Ensure yq is available
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        set -euo pipefail
        
        # Determine repo root - composite actions might run in different contexts
        REPO_ROOT="${GITHUB_WORKSPACE:-.}"
        cd "${REPO_ROOT}"
        
        # Add tools/bin to PATH for this step AND subsequent steps
        # $GITHUB_PATH takes effect in NEXT step, so we also export locally
        echo "${REPO_ROOT}/tools/bin" >> "$GITHUB_PATH"
        export PATH="${REPO_ROOT}/tools/bin:$PATH"

        YQ_VER_TRIM="${YQ_VERSION#v}"

        # Ensure scripts are executable
        chmod +x "${REPO_ROOT}/scripts/tools/yq-pin.sh"

        # Pinned Version erzwingen (Download + Verifikation)
        # The script uses BASH_SOURCE to find ROOT_DIR, so it will work from any location
        "${REPO_ROOT}/scripts/tools/yq-pin.sh" ensure

        # Re-export PATH to ensure tools/bin is prioritized after yq-pin.sh runs
        export PATH="${REPO_ROOT}/tools/bin:$PATH"

        # Final verification - check both in PATH and at explicit location
        if [[ -x "${REPO_ROOT}/tools/bin/yq" ]]; then
          YQ_BIN="${REPO_ROOT}/tools/bin/yq"
        elif command -v yq >/dev/null; then
          YQ_BIN="$(command -v yq)"
        else
          echo "yq installation failed: binary not found at ${REPO_ROOT}/tools/bin/yq and not in PATH" >&2
          exit 1
        fi

        YQ_VERSION_OUTPUT="$("${YQ_BIN}" --version)"
        echo "${YQ_VERSION_OUTPUT}"
        if ! echo "${YQ_VERSION_OUTPUT}" | grep -q "version v${YQ_VER_TRIM}"; then
          echo "yq version check failed. Expected v${YQ_VER_TRIM}, got: ${YQ_VERSION_OUTPUT}" >&2
          exit 1
        fi

        echo "✅ yq ${YQ_VER_TRIM} verified OK at ${YQ_BIN}"
