name: 'Setup just'
description: 'Install just using version from toolchain.versions.yml (fallback to safe defaults)'
runs:
  using: 'composite'
  steps:
    - name: Install just (fallback)
      shell: bash
      run: |
        set -euo pipefail

        # Recommend pinning in toolchain.versions.yml: just: "v0.11.0"
        # Uses JUST_VERSION env var if set (e.g. by previous step reading toolchain),
        # otherwise defaults to v0.11.0.
        JUST_VERSION="${JUST_VERSION:-v0.11.0}"
        mkdir -p "$HOME/.local/bin"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

        if command -v just >/dev/null 2>&1; then
          echo "just already installed: $(just --version)"
          exit 0
        fi

        # macOS: prefer brew
        if command -v brew >/dev/null 2>&1; then
          brew install just || true
        fi

        # Debian/Ubuntu: try package manager (best-effort)
        if command -v apt-get >/dev/null 2>&1; then
          sudo apt-get update
          sudo apt-get install -y just || true
        fi

        # If Rust toolchain present, install via cargo (deterministic & reproducible)
        # Fallback mechanism: Try cargo first if available (but continue if it fails to try download)
        if command -v cargo >/dev/null 2>&1; then
          if cargo install --locked --version "${JUST_VERSION#v}" just; then
            echo "Installed just via cargo"
            exit 0
          else
            echo "cargo install failed, falling back to prebuilt binary download..."
          fi
        fi

        # Final attempt: download prebuilt binary from upstream releases (best-effort).
        OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
        ARCH_RAW="$(uname -m)"
        case "$OS" in
          linux)
            case "$ARCH_RAW" in
              x86_64) TARGET="x86_64-unknown-linux-musl" ;;
              aarch64) TARGET="aarch64-unknown-linux-musl" ;;
              *) echo "Unsupported Linux architecture: $ARCH_RAW" >&2; exit 1 ;;
            esac
            ;;
          darwin)
            case "$ARCH_RAW" in
              x86_64) TARGET="x86_64-apple-darwin" ;;
              arm64) TARGET="aarch64-apple-darwin" ;;
              *) echo "Unsupported macOS architecture: $ARCH_RAW" >&2; exit 1 ;;
            esac
            ;;
          *) echo "Unsupported OS: $OS" >&2; exit 1 ;;
        esac

        TMP_DIR="$(mktemp -d)"
        RELEASE_TAG="${JUST_VERSION#v}"
        ASSET="just-${RELEASE_TAG}-${TARGET}.tar.gz"
        # NOTE: casey/just releases use raw tags (e.g. 1.43.0) in download URLs, not v-prefixed.
        URL="https://github.com/casey/just/releases/download/${RELEASE_TAG}/${ASSET}"

        if curl -fsSL -o "${TMP_DIR}/${ASSET}" "${URL}"; then
          tar -xzf "${TMP_DIR}/${ASSET}" -C "${TMP_DIR}"
          install -m 0755 "${TMP_DIR}/just" "$HOME/.local/bin/just" || true
          rm -rf "${TMP_DIR}"
        else
          echo "Failed to download prebuilt just from ${URL} — please pin a valid asset or install via cargo/brew/apt" >&2
        fi

        if command -v just >/dev/null 2>&1; then
        just --version
        else
        echo "Installation of just failed; please update CI step to a valid installer or vendor the action." >&2
        exit 1
        fi
